import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync, statSync } from "node:fs"
import { join, relative, resolve, sep } from "node:path"
import { type Plugin, tool } from "@opencode-ai/plugin"

type Source = { type: string; reference: string; location: string }
type Record = { file: string; path: string; text: string; id: string; title: string; classification: string; confidence: string; source: string; location: string; sources: Source[]; relations: string[]; conflict: boolean; conflictStatus: string }
const headings = ["Evidence Map", "Found Information", "Inferences", "Gaps", "Conflicts", "Risks", "Questions", "Sources"]
const invalidProject = (name: string) => !name || name.includes("/") || name.includes("\\") || name === "." || name === ".."
const directory = (path: string) => existsSync(path) && !lstatSync(path).isSymbolicLink() && statSync(path).isDirectory()
const inside = (root: string, path: string) => { const result = relative(root, path); return result === "" || (!result.startsWith(`..${sep}`) && result !== "..") }
const safeFile = (root: string, path: string) => { try { return existsSync(path) && !lstatSync(path).isSymbolicLink() && inside(root, realpathSync(path)) } catch { return false } }
const field = (text: string, name: string) => (text.match(new RegExp(`^${name}:\\s*(?:["']([^"']*)["']|(.+?))\\s*$`, "m"))?.slice(1).find(Boolean) || "").trim().replace(/^(null|~|false)$/i, "")
const list = (text: string, name: string) => { const flow = text.match(new RegExp(`^${name}:\\s*\\[([^\\]]*)\\]\\s*$`, "m"))?.[1]; if (flow !== undefined) return flow.split(",").map((value) => value.trim().replace(/^["']|["']$/g, "")).filter(Boolean); const body = text.match(new RegExp(`^${name}:\\s*$([\\s\\S]*?)(?=^[a-z_]+:|^---\\s*$)`, "m"))?.[1] || ""; return [...body.matchAll(/^\s*-\s*(.+?)\s*$/gm)].map((match) => match[1]) }
const provenance = (text: string, name: string) => { const block = text.match(/^provenance:\s*$([\s\S]*?)(?=^[a-z_]+:|^---\s*$)/m)?.[1] || ""; return (block.match(new RegExp(`^\\s{2}${name}:\\s*(.+?)\\s*$`, "m"))?.[1] || "").trim() }
const provenanceSources = (text: string): Source[] => { const lines = text.split(/\r?\n/), start = lines.findIndex((line) => /^\s{2}sources:\s*$/.test(line)), entries: string[][] = []; if (start < 0) return []; for (const line of lines.slice(start + 1)) { if (/^\s{2}[a-z_]+:/.test(line) || line === "---") break; if (/^\s{4}-\s*type:/.test(line)) entries.push([line]); else if (entries.length) entries[entries.length - 1].push(line) } return entries.map((entry) => { const value = (name: string) => entry.join("\n").match(new RegExp(`^\\s*(?:-\\s*)?${name}:\\s*(.+?)\\s*$`, "m"))?.[1]?.trim() || ""; return { type: value("type"), reference: value("reference"), location: value("location") } }).filter((source) => source.reference) }
const conflictStatus = (text: string) => text.match(/^conflict:\s*$([\s\S]*?)(?=^[a-z_]+:|^---\s*$)/m)?.[1].match(/^\s{2}status:\s*(.+?)\s*$/m)?.[1].trim() || "unspecified"
const registryWikiUrls = (text: string) => ["Functional ADO Wiki", "Technical ADO Wiki"].flatMap((name) => [...section(text, name).matchAll(/^\s*-\s*URL:\s*`(https:\/\/dev\.azure\.com\/[^\s`]+\/_[Ww]iki\/[^\s`]+)`\s*$/gm)].map((match) => ({ category: "Wiki Search and Read", reference: match[1] })))
const section = (text: string, name: string) => { const lines = text.split(/\r?\n/), start = lines.findIndex((line) => line === `## ${name}`), end = lines.findIndex((line, index) => index > start && line.startsWith("## ")); return start < 0 ? "" : lines.slice(start + 1, end < 0 ? undefined : end).join("\n") }
const localLinks = (text: string) => ["Related Evidence and Decisions", "Related Items", "Related Evidence and Items", "Outputs", "Questions", "Conflicts"].flatMap((name) => [...section(text, name).matchAll(/\[[^\]]+\]\(([^)#]+)(?:#[^)]+)?\)/g)].map((match) => match[1]))
const relationDisputedBy = (conflict: Record, relation: string, target: Record | undefined) => conflict.conflict && conflict.conflictStatus.toLowerCase() === "open" && [...conflict.sources.map((source) => source.reference), ...conflict.relations, ...list(conflict.text, "related_items")].some((reference) => reference === relation || (target && reference.endsWith(`/${target.id}`)) || reference === target?.id)
function read(root: string, file: string, displayRoot: string): Record {
  const text = readFileSync(file, "utf8"), sources = provenanceSources(text), source = sources[0]
  return { file, path: relative(displayRoot, file).split(sep).join("/"), text, id: field(text, "id"), title: field(text, "title"), classification: provenance(text, "classification") || "Unclassified", confidence: provenance(text, "confidence") || "unspecified", source: source?.reference || relative(displayRoot, file).split(sep).join("/"), location: source?.location || "Document", sources, relations: list(text, "ado_relation_references"), conflict: provenance(text, "classification") === "Conflict", conflictStatus: conflictStatus(text) }
}
function candidates(project: string, root: string) {
  const result: string[] = [], features = join(project, "features"), ideas = join(project, "ideas")
  if (directory(features)) for (const feature of readdirSync(features)) { const featureRoot = join(features, feature), file = join(featureRoot, "feature.md"); if (/^F-[^-]+-.+$/.test(feature) && safeFile(root, file)) result.push(file); const stories = join(featureRoot, "user-stories"); if (directory(stories)) for (const story of readdirSync(stories)) { const storyFile = join(stories, story, "user-story.md"); if (/^US-[^-]+-.+$/.test(story) && safeFile(root, storyFile)) result.push(storyFile) } }
  if (directory(ideas)) for (const idea of readdirSync(ideas)) { const file = join(ideas, idea, "idea.md"); if (/^IDEA-[^-]+-.+$/.test(idea) && safeFile(root, file)) result.push(file) }
  return result
}
function matches(item: Record, filters: globalThis.Record<string, string>) {
  return Object.entries(filters).every(([key, raw]) => { const value = String(raw || "").trim().toLowerCase(); if (!value) return true; if (key === "id") return item.id.toLowerCase() === value; if (key === "text") return item.text.toLowerCase().includes(value); if (key === "url") return item.text.toLowerCase().includes(value); if (key === "tag") return list(item.text, "tags").some((tag) => tag.toLowerCase() === value); return field(item.text, key).toLowerCase() === value })
}
const cited = (item: Record, directness: string, relationship: string) => `[source: ${item.source}; location: ${item.location}; classification: ${item.classification}; confidence: ${item.confidence}; directness: ${directness}; relationship: ${relationship}]`
function report(scope: string, status: string, coverage: string, entries: globalThis.Record<string, string[]>) { return [`# Discovery Report: ${scope}`, `Status: ${status}`, `Coverage: ${coverage}`, "## Evidence Map", "### Nodes", ...(entries.Nodes || ["- None."]), "### Edges", ...(entries.Edges || ["- None."]), ...headings.slice(1).flatMap((heading) => [`## ${heading}`, ...(entries[heading] || ["- None."])])].join("\n\n") }

export const BassDiscoveryReportPlugin: Plugin = async () => ({ tool: { bass_discovery_report: tool({ description: "Deterministically discover bounded local BASS context without MCP calls or mutations.", args: { projectName: tool.schema.string().optional(), filters: tool.schema.object() }, async execute(args: { projectName?: string; filters: globalThis.Record<string, string> }, context) {
  const filters = args.filters || {}, allowed = new Set(["id", "url", "text", "type", "tag", "state", "area", "iteration"]), supplied = Object.entries(filters)
  if (!supplied.length || supplied.some(([key, value]) => !allowed.has(key) || typeof value !== "string" || !value.trim())) return report("invalid filters", "blocked", "No filesystem sources loaded.", { Gaps: ["- Supply one or more nonempty string values using only id, url, text, type, tag, state, area, or iteration [source: input; location: filters; classification: Fact; confidence: high; directness: direct]."] })
  const name = args.projectName?.trim(), projects = join(context.directory, "BASS", "projects")
  if (name && invalidProject(name)) return report("invalid project", "blocked", "No filesystem sources loaded because projectName failed preflight.", { Gaps: ["- Selected project is invalid [source: input; location: projectName; classification: Fact; confidence: high; directness: direct]."] })
  if (!directory(projects)) return report("unavailable project", "blocked", "BASS/projects is unavailable.", { Gaps: ["- Project root is unavailable [source: BASS/projects; location: filesystem; classification: Fact; confidence: high; directness: direct]."] })
  const names = readdirSync(projects).filter((candidate) => directory(join(projects, candidate))), selected = name || (names.length === 1 ? names[0] : "")
  if (!selected || !names.includes(selected)) return report(selected || "unspecified", "blocked", "Selected project is unavailable.", { Gaps: ["- Selected project is unavailable [source: BASS/projects; location: filesystem; classification: Fact; confidence: high; directness: direct]."] })
  const project = join(projects, selected); if (lstatSync(project).isSymbolicLink()) return report(selected, "blocked", "Selected project containment cannot be verified.", { Gaps: ["- Selected project is a symbolic link or junction [source: BASS/projects; location: filesystem; classification: Fact; confidence: high; directness: direct]."] })
  const root = realpathSync(project), all = candidates(project, root).map((file) => read(root, file, context.directory)), found = all.filter((item) => matches(item, filters))
  if (!found.length) return report("no local match", "blocked", `Searched ${selected} Feature, User Story, and Idea records; no record matched all supplied filters.`, { Gaps: ["- No local item satisfies every supplied filter [source: local records; location: selected project; classification: Fact; confidence: high; directness: direct]."] })
  const nodes: { item: Record; directness: string; relationship: string }[] = found.map((item) => ({ item, directness: "direct", relationship: "matched" })), edges: { origin: Record; item: Record; relationship: string }[] = []
  const add = (item: Record | undefined, relationship: string, origin: Record) => { if (!item) return; edges.push({ origin, item, relationship }); if (!nodes.some((node) => node.item.file === item.file)) nodes.push({ item, directness: "one-hop", relationship }) }
  for (const item of found) { const parent = field(item.text, "parent_feature_id"), linked = localLinks(item.text).flatMap((link) => { const file = resolve(join(item.file, ".."), link); return safeFile(root, file) ? [read(root, file, context.directory)] : [] }); if (parent) add(all.find((candidate) => candidate.id === parent), "parent", item); for (const child of all.filter((candidate) => field(candidate.text, "parent_feature_id") === item.id)) add(child, "child", item); for (const relation of item.relations) { const target = all.find((candidate) => candidate.id === relation || relation.endsWith(`/${candidate.id}`)); if (!linked.some((conflict) => relationDisputedBy(conflict, relation, target))) add(target, "related", item) } for (const artifact of linked) add(artifact, "local artifact", item) }
  const entries: globalThis.Record<string, string[]> = { Nodes: nodes.map((node) => `- ${node.item.id || node.item.title} (${node.relationship}) ${cited(node.item, node.directness, node.relationship)}`), Edges: edges.map((edge) => `- ${edge.origin.id || edge.origin.title} -> ${edge.item.id || edge.item.title} (${edge.relationship}) ${cited(edge.item, "one-hop", edge.relationship)}`), "Found Information": found.map((item) => `- ${item.id || item.title} was found locally ${cited(item, "direct", "matched")}`), Inferences: [], Gaps: [], Conflicts: [], Risks: [], Questions: [], Sources: nodes.map((node) => `- ${node.item.path} ${cited(node.item, node.directness, node.relationship)}`) }
  for (const node of nodes.filter((node) => node.item.conflict)) { const sources = node.item.sources.map((source) => `${source.type}: ${source.reference} (${source.location})`).join("; "); entries.Conflicts.push(`- ${node.item.id || node.item.title} status: ${node.item.conflictStatus}; competing sources: ${sources} ${cited(node.item, node.directness, node.relationship)}`); if (node.item.conflictStatus.toLowerCase() === "open") { entries.Risks.push(`- The disputed dependency is isolated and cannot support a dependency conclusion ${cited(node.item, node.directness, node.relationship)}`); entries.Questions.push(`- What decision resolves ${node.item.id || node.item.title}? ${cited(node.item, node.directness, node.relationship)}`) } }
  const registry = join(project, "project-context", "context-registry.md"), required = new Set<string>(); if (found.some((item) => item.relations.length || field(item.text, "ado_work_item_id") || field(item.text, "ado_work_item_url"))) { required.add("Work Item Search and Filtering"); required.add("Hierarchy and Relations") } if (found.some((item) => item.sources.some((source) => source.type === "ado_comment"))) required.add("Comments and History"); if (found.some((item) => item.sources.some((source) => source.type === "ado_wiki")) || (safeFile(root, registry) && registryWikiUrls(readFileSync(registry, "utf8")).length)) required.add("Wiki Search and Read")
  for (const category of required) { const citation = `[source: local configuration; location: selected records; classification: Fact; confidence: high; directness: direct]`, questionCitation = `[source: none; location: ${category}; classification: Question; confidence: low; directness: direct; evidence_gap: local-only tool did not execute the required category]`; entries.Gaps.push(`- Required ${category} is not executed by this local-only tool ${citation}.`); entries.Risks.push(`- Risk: ${category} remains unexecuted and may leave discovery incomplete ${citation}.`); entries.Questions.push(`- Question: What evidence from ${category} is needed to complete discovery? ${questionCitation}.`) }
  const status = entries.Gaps.length || entries.Conflicts.length ? "warning" : "ready"
  return JSON.stringify(report(found.map((item) => item.id || item.title).join(", "), status, `Searched ${selected} local records; ${required.size} mapped ADO category gap(s) remain unexecuted. [source: local discovery; location: complete local search and unexecuted mapped ADO categories; classification: Fact; confidence: high; directness: direct]`, entries))
} }) } })
