import { createHash, randomUUID } from "node:crypto"
import { existsSync, lstatSync, readdirSync, realpathSync, readFileSync, statSync } from "node:fs"
import { dirname, join, relative, sep } from "node:path"
import { type Plugin, tool } from "@opencode-ai/plugin"

type Evidence = { type: string; source: string; location: string; classification: string; confidence: string; claim?: string; relatedItemId?: string }
type Record = { id: string; type: string; file: string; directory: string }
type Issued = { projectName: string; artifactType: string; id: string; title: string; directory: string; markdown: string; hash: string; evidence: Evidence[]; parent?: Record }
const issued = ((globalThis as any).__bassCreatorIssuedPreviews ||= new Map<string, Issued>()) as Map<string, Issued>
const types = new Set(["feature", "user_story", "acceptance_criteria", "proposal"]), evidenceTypes = new Set(["local_file", "ado_wiki", "ado_work_item", "ado_comment", "ado_pull_request", "ado_pipeline"]), classes = new Set(["Fact", "Inference", "Assumption", "Proposal", "Question", "Conflict", "Decision"])
const badProject = (v: string) => !v || /[\\/]/.test(v) || v === "." || v === ".."
const dir = (p: string) => existsSync(p) && !lstatSync(p).isSymbolicLink() && statSync(p).isDirectory()
const within = (root: string, p: string) => { const r = relative(root, p); return r === "" || (!r.startsWith(`..${sep}`) && r !== "..") }
const file = (root: string, p: string) => { try { return existsSync(p) && !lstatSync(p).isSymbolicLink() && within(root, realpathSync(p)) } catch { return false } }
const field = (text: string, key: string) => text.match(new RegExp(`^${key}:\\s*(.+?)\\s*$`, "m"))?.[1].replace(/["']/g, "").trim() || ""
const slug = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "untitled"
const digest = (v: string) => createHash("sha256").update(v, "utf8").digest("hex")
function records(project: string, root: string): Record[] { const out: Record[] = [], features = join(project, "features"); if (!dir(features)) return out; for (const name of readdirSync(features)) { const folder = join(features, name), feature = join(folder, "feature.md"); if (!file(root, feature)) continue; const id = field(readFileSync(feature, "utf8"), "id"); out.push({ id, type: "feature", file: feature, directory: folder }); const stories = join(folder, "user-stories"); if (dir(stories)) for (const story of readdirSync(stories)) { const storyFile = join(stories, story, "user-story.md"); if (file(root, storyFile)) out.push({ id: field(readFileSync(storyFile, "utf8"), "id"), type: "user_story", file: storyFile, directory: join(stories, story) }) } } return out }
function id(type: string, project: string, root: string) { const prefix = type === "feature" ? "F" : type === "user_story" ? "US" : "PRO", source = type === "proposal" ? (() => { const out: number[] = [], proposals = join(project, "proposals"); if (!dir(proposals)) return out; for (const name of readdirSync(proposals)) { const proposal = join(proposals, name, "proposal.md"); if (file(root, proposal)) out.push(Number(field(readFileSync(proposal, "utf8"), "id").match(/^PRO-(\d+)$/)?.[1] || 0)) } return out })() : records(project, root).map((r) => Number(r.id.match(new RegExp(`^${prefix}-(\\d+)$`))?.[1] || 0)); return `${prefix}-${String(Math.max(0, ...source) + 1).padStart(3, "0")}` }
const blocked = (message: string, markdown = "", gaps = [message], questions: string[] = [], conflicts: string[] = []) => ({ previewId: "", writeStatus: "blocked", artifactMarkdown: markdown, gaps, questions, conflicts })
function render(id: string, type: string, title: string, evidence: Evidence[], assumptions: Evidence[], related: Record[], artifact = "", target = "") {
  const basis = evidence.find((e) => e.classification === "Fact" || e.classification === "Inference") || evidence[0] || assumptions[0], claim = basis.claim || "the cited context applies", citations = evidence.map((e) => `- ${e.claim || "No claim supplied."} [source: ${e.source}; type: ${e.type}; location: ${e.location}; classification: ${e.classification}; confidence: ${e.confidence}]`).join("\n"), rows = evidence.map((e) => `| ${e.classification} | ${e.type} | ${e.source} | ${e.location} | ${e.confidence} | ${e.claim || "No claim supplied."} |`).join("\n"), criteria = `### AC-001: ${title}\n\n- Given ${claim}\n- When the user performs the proposed action\n- Then the observable outcome meets the cited need\n- Evidence or assumption: ${basis.classification} [source: ${basis.source}; type: ${basis.type}; location: ${basis.location}; confidence: ${basis.confidence}]`
  if (type === "acceptance_criteria") return `# Acceptance Criteria Update: ${target}\n\n## Acceptance Criteria\n\n${criteria}${[...evidence.filter((e) => e.classification === "Assumption"), ...assumptions].map((e) => `\n\n### Assumptions\n\n- ${e.claim || e.source} [classification: Assumption; source: ${e.source}; location: ${e.location}; confidence: ${e.confidence}]`).join("")}\n\n## Changelog\n\n- 2026-08-14: Proposed approval-bound update for ${target}.`
  const front = [`---`, `id: ${id}`, `title: "${title.replace(/"/g, "'")}"`, "version: v1.0", "created_date: 2026-08-14", "updated_date: 2026-08-14", "derived_from: null", "supersedes: null", ...(type === "user_story" ? [`parent_feature_id: ${target}`] : []), "ado_work_item_id: null", "ado_work_item_url: null", "provenance:", "  classification: Proposal", "  sources:", ...evidence.map((e) => `    - type: ${e.type}\n      reference: ${e.source}\n      location: "${e.location}"\n      retrieved_date: 2026-08-14`), "  actor: BASS", "  date: 2026-08-14", "  confidence: high", "  source_version: v1.0", ...(related.length ? ["  related_items:", ...related.map((r) => `    - ${r.id}`)] : []), "---"].join("\n")
  const proposal = type === "proposal" ? `## Problem or Opportunity\n\n${claim}\n\n## Proposed Change\n\n${title}\n\n## Expected Value\n\nAddress the cited opportunity.\n\n## Scope\n\n${citations}\n\n## Out of Scope\n\n- None identified.\n\n## Rules\n\n- None identified.\n\n## Dependencies\n\n- None identified.\n\n## Risks\n\n- None identified.\n\n## Next Step\n\n- Review this proposal with the cited evidence.` : `${type === "user_story" ? `## User Story\n\nAs a user, I want ${title.toLowerCase()} so that the cited need is addressed.\n\n` : ""}## Goal\n\n${claim}\n\n## Scope\n\n${citations}\n\n## Out of Scope\n\n- None identified.\n\n## Business Rules\n\n- None identified.\n\n## Dependencies\n\n- None identified.\n\n## Risks\n\n- None identified.`
  return `${front}\n\n# ${type === "feature" ? "Feature" : type === "user_story" ? "User Story" : "Functional Proposal"}: ${title}\n\n${proposal}\n\n## Assumptions\n\n${[...evidence.filter((e) => e.classification === "Assumption"), ...assumptions].map((e) => `- ${e.claim || e.source} [classification: Assumption; source: ${e.source}; location: ${e.location}; confidence: ${e.confidence}]`).join("\n") || "- None."}\n\n## Questions\n\n${evidence.filter((e) => e.classification === "Question").map((e) => `- ${e.claim || e.source}`).join("\n") || "- None."}\n\n## Cited Evidence\n\n| Classification | Source type | Source | Location | Confidence | Claim or relevance |\n| --- | --- | --- | --- | --- | --- |\n${rows}\n\n## Given/When/Then Acceptance Criteria\n\n${criteria}\n\n## ADO Link\n\n- Local preview only; no ADO operation occurred.\n\n## Related Evidence and Decisions\n\n${related.map((r) => `- [${r.id}](${relative(dirname(artifact), r.file).split(sep).join("/")})`).join("\n") || citations}\n\n## Changelog\n\n| Date | Version | Change | Reason | Related records |\n| --- | --- | --- | --- | --- |\n| 2026-08-14 | v1.0 | Initial preview. | Awaiting explicit approval. | ${related.map((r) => r.id).join(", ") || evidence.map((e) => e.source).join(", ")} |`
}
export const BassCreatorPreviewPlugin: Plugin = async () => ({ tool: { bass_creator_preview: tool({ description: "Create deterministic local-only BASS previews without network or remote operations.", args: { projectName: tool.schema.string().optional(), artifactType: tool.schema.string(), title: tool.schema.string(), evidence: tool.schema.array(tool.schema.object()), assumptions: tool.schema.array(tool.schema.string()).optional(), targetId: tool.schema.string().optional(), promoteTo: tool.schema.string().optional() }, async execute(args: any, context: any) {
  const name = String(args.projectName || "").trim(), type = String(args.artifactType || ""), title = String(args.title || "").trim(), evidence = Array.isArray(args.evidence) ? args.evidence as Evidence[] : [], assumptions = args.assumptions === undefined ? [] : Array.isArray(args.assumptions) ? args.assumptions.map((assumption: unknown) => String(assumption).trim()) : [], explicitAssumptions = assumptions.map((claim) => ({ type: "explicit_input", source: "explicit_input", location: "assumptions", classification: "Assumption", confidence: "unverified", claim })), projects = join(context.directory, "BASS", "projects"); if (badProject(name) || !dir(projects)) return JSON.stringify(blocked("Selected project is invalid or unavailable.")); const project = join(projects, name); if (!dir(project) || lstatSync(project).isSymbolicLink()) return JSON.stringify(blocked("Selected project containment cannot be verified.")); const root = realpathSync(project)
  if (!types.has(type) || !title || (!evidence.length && !assumptions.length) || evidence.some((e) => !e || !evidenceTypes.has(e.type) || !e.source || !e.location || !classes.has(e.classification) || !e.confidence) || assumptions.some((assumption) => !assumption)) return JSON.stringify(blocked("Input requires a supported artifact type, title, and typed complete cited evidence or explicit assumptions."))
  const ungroundedQuestions = evidence.filter((e) => e.classification === "Question").map((e) => e.claim || e.source), ungroundedConflicts = evidence.filter((e) => e.classification === "Conflict").map((e) => e.claim || e.source)
  const all = records(project, root), parent = type === "user_story" ? all.filter((r) => r.type === "feature" && r.id === args.targetId) : [], target = type === "acceptance_criteria" ? all.filter((r) => r.id === args.targetId) : [], newId = type === "acceptance_criteria" ? String(args.targetId) : id(type, project, root), artifactFile = type === "proposal" ? join(project, "proposals", `${newId}-${slug(title)}`, "proposal.md") : type === "user_story" ? join(parent[0]?.directory || "", "user-stories", `${newId}-${slug(title)}`, "user-story.md") : join(project, "features", `${newId}-${slug(title)}`, "feature.md"), related = evidence.map((e) => { const candidate = join(root, e.source), actual = file(root, candidate) ? field(readFileSync(candidate, "utf8"), "id") : "", requested = String(e.relatedItemId || ""); return /^(?:EVD|DEC)-[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$/.test(actual) && (requested === actual || (!requested && new RegExp(`\\b${actual}\\b`).test(`${e.source} ${e.claim || ""}`))) ? { id: actual, type: "related", file: candidate, directory: dirname(candidate) } : undefined }).filter((r): r is Record => Boolean(r)).filter((r, i, values) => values.findIndex((other) => other.id === r.id) === i); if (!evidence.some((e) => e.classification === "Fact" || e.classification === "Inference")) return JSON.stringify(blocked("Evidence requires at least one Fact or Inference.", render(newId, type, title, evidence, explicitAssumptions, related, artifactFile, String(args.targetId || "")), ["Evidence has no Fact or Inference."], ungroundedQuestions, ungroundedConflicts))
  if ((type === "user_story" && parent.length !== 1) || (type === "acceptance_criteria" && target.length !== 1)) return JSON.stringify(blocked("Target must resolve to one canonical existing record."))
  const conflicts = evidence.filter((e) => e.classification === "Conflict").map((e) => e.claim || e.source), questions = evidence.filter((e) => e.classification === "Question").map((e) => e.claim || e.source), gaps = conflicts.length ? ["Resolve cited conflicts before approval or ADO preview."] : [], artifact = render(newId, type, title, evidence, explicitAssumptions, related, artifactFile, String(args.targetId || "")); if (conflicts.length) return JSON.stringify(blocked("Preview is incomplete or conflicted.", artifact, gaps, questions, conflicts))
  const previewId = randomUUID(), integrityHash = digest(artifact), adoPreview = (type === "feature" || type === "user_story" || (type === "proposal" && ["feature", "user_story"].includes(args.promoteTo))) ? { type: type === "proposal" ? (args.promoteTo === "user_story" ? "User Story" : "Feature") : type === "user_story" ? "User Story" : "Feature", title, description: artifact.match(/## (?:Goal|Problem or Opportunity)\n\n([^\n]+)/)?.[1] || title, acceptanceCriteria: artifact.match(/## Given\/When\/Then Acceptance Criteria\n\n([\s\S]*?)(?=\n\n## )/)?.[1] || "", parentOrLinkTarget: parent[0]?.id || null, tags: [], area: null, iteration: null, priority: null, effort: null, unavailableMappings: ["tags", "area", "iteration", "priority", "effort"] } : undefined
  issued.set(previewId, { projectName: name, artifactType: type, id: newId, title, directory: `${newId}-${slug(title)}`, markdown: artifact, hash: integrityHash, evidence, parent: type === "acceptance_criteria" ? target[0] : parent[0] }); return JSON.stringify({ previewId, writeStatus: "ready_for_approval", artifactMarkdown: artifact, integrityHash, adoPreview, gaps, questions, conflicts })
} }) } })
