import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { type Plugin, tool } from "@opencode-ai/plugin"

const categories = ["Repository and File Search", "Pull Request Details, Comments, and Links", "Work Item Association", "Pipeline and Deployment Status"]
const resources: Record<string, Set<string>> = { "Repository and File Search": new Set(["repository"]), "Pull Request Details, Comments, and Links": new Set(["pull_request"]), "Work Item Association": new Set(["commit", "pull_request"]), "Pipeline and Deployment Status": new Set(["pipeline", "deployment"]) }
const field = (text: string, name: string) => text.match(new RegExp(`^${name}:[ \\t]*(\\S(?:.*\\S)?)[ \\t]*$`, "m"))?.[1].trim() || ""
const section = (text: string, heading: string) => text.match(new RegExp(`^## ${heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[ \\t]*\\r?\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, "m"))?.[1] || ""
export function validateAdoTechnicalDeliveryCapabilities({ projectDirectory, requiredCategories = [] }: { projectDirectory: string, requiredCategories?: string[] }) {
  const text = existsSync(join(projectDirectory, "project-context", "ado-technical-delivery-capabilities.md")) ? readFileSync(join(projectDirectory, "project-context", "ado-technical-delivery-capabilities.md"), "utf8") : ""
  const mappings = Object.fromEntries(categories.map(category => { const block = section(text, category), toolName = field(block, "toolName"), supportedInput = field(block, "supportedInput"), verificationDate = field(block, "verificationDate"), resourceType = field(block, "resourceType"), verifiedReadOnly = /^verifiedReadOnly:\s*true\s*$/mi.test(block), operation = field(block, "operation").toLowerCase(), valid = /^ado_[A-Za-z0-9_-]+$/.test(toolName) && supportedInput && verifiedReadOnly && /^\d{4}-\d{2}-\d{2}$/.test(verificationDate) && !Number.isNaN(new Date(`${verificationDate}T00:00:00Z`).valueOf()) && resources[category].has(resourceType) && !/(create|update|delete|write|merge|approve|queue|cancel|deploy|mutat)/.test(operation) && block.split(/\r?\n/).every(line => !line.trim() || /^(toolName|supportedInput|verifiedReadOnly|verificationDate|resourceType|operation):/.test(line.trim())); return [category, { toolName, supportedInput, verifiedReadOnly, verificationDate, resourceType, valid: Boolean(valid) }] })) as Record<string, any>
  const required = [...new Set(requiredCategories)].filter(category => categories.includes(category))
  return { mappings, permissionFragment: [`"ado_*": deny`, ...categories.filter(category => mappings[category].valid).map(category => `"${mappings[category].toolName}": allow`)].join("\n"), dispatch: required.filter(category => mappings[category].valid).map(category => ({ category, toolName: mappings[category].toolName })), unmappedGaps: required.filter(category => !mappings[category].valid) }
}
export const BassValidateAdoTechnicalDeliveryCapabilitiesPlugin: Plugin = async () => ({ tool: { bass_validate_ado_technical_delivery_capabilities: tool({ description: "Validate mapped read-only technical-delivery capabilities without ADO or MCP calls.", args: { projectDirectory: tool.schema.string(), requiredCategories: tool.schema.array(tool.schema.string()) }, async execute(args: { projectDirectory: string, requiredCategories?: string[] }) { return JSON.stringify(validateAdoTechnicalDeliveryCapabilities(args)) } }) } })
