import { createHash } from "node:crypto"
import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs"
import { join, relative, sep } from "node:path"
import { type Plugin, tool } from "@opencode-ai/plugin"

const issued = ((globalThis as any).__bassCreatorIssuedPreviews ||= new Map()) as Map<string, any>
const hash = (v: string) => createHash("sha256").update(v, "utf8").digest("hex")
const badProject = (v: string) => !v || /[\\/]/.test(v) || v === "." || v === ".."
const within = (root: string, p: string) => { const r = relative(root, p); return r === "" || (!r.startsWith(`..${sep}`) && r !== "..") }
const safe = (root: string, p: string) => { try { return existsSync(p) && !lstatSync(p).isSymbolicLink() && within(root, realpathSync(p)) } catch { return false } }
const blocked = (message: string) => ({ status: "blocked", message })
const field = (text: string, key: string) => text.match(new RegExp(`^${key}:\\s*(.+?)\\s*$`, "m"))?.[1].replace(/["']/g, "").trim() || ""
const nextVersion = (version: string) => { const match = version.match(/^v(\d+)\.(\d+)$/); return match ? `v${match[1]}.${Number(match[2]) + 1}` : "v1.1" }
export const BassPersistApprovedArtifactPlugin: Plugin = async () => ({ tool: { bass_persist_approved_artifact: tool({ description: "Persist one matching approved local BASS preview without remote operations.", args: { projectName: tool.schema.string(), previewId: tool.schema.string(), approved: tool.schema.boolean(), integrityHash: tool.schema.string(), approvedArtifactMarkdown: tool.schema.string() }, async execute(args: any, context: any) {
  const name = String(args.projectName || "").trim(), preview = issued.get(args.previewId), markdown = String(args.approvedArtifactMarkdown || ""), projects = join(context.directory, "BASS", "projects"); if (badProject(name) || !safe(context.directory, join(context.directory, "BASS")) || !safe(join(context.directory, "BASS"), projects)) return blocked("Project root is unavailable."); const project = join(projects, name); if (!safe(projects, project)) return blocked("Selected project containment cannot be verified."); const root = realpathSync(project)
  if (!args.approved || !preview || preview.projectName !== name || preview.hash !== args.integrityHash || preview.hash !== hash(markdown) || preview.markdown !== markdown) return blocked("Approval, preview identity, and complete payload hash must match an issued ready preview.")
  if (preview.artifactType === "acceptance_criteria") {
   const artifact = preview.parent?.file, registers = [join(project, "evidence-register.md"), join(project, "decision-log.md"), join(project, "action-log.md")], criteria = markdown.match(/## Acceptance Criteria\n\n([\s\S]*?)(?=\n\n## Changelog)/)?.[1]
   if (!artifact || !criteria || !safe(root, artifact) || registers.some((p) => !safe(root, p))) return blocked("Canonical target, register, or containment preflight failed.")
   const original = readFileSync(artifact, "utf8"), previousVersion = field(original, "version"), version = nextVersion(previousVersion), id = field(original, "id") || preview.id, changelog = `| 2026-08-14 | ${version} | Approved acceptance-criteria update. | Explicit approval for preview ${args.previewId}. | ${id} |`, updated = original.replace(/(## (?:Given\/When\/Then )?Acceptance Criteria\n\n)[\s\S]*?(?=\n\n## Changelog)/, `$1${criteria}`).replace(/^version:\s*.+$/m, `version: ${version}`).replace(/^updated_date:\s*.+$/m, "updated_date: 2026-08-14").replace(/^derived_from:\s*.+$/m, `derived_from: ${id}@${previousVersion}`).replace(/^supersedes:\s*.+$/m, `supersedes: ${id}@${previousVersion}`).replace(/(## Changelog\n\n[\s\S]*)$/, `$1\n${changelog}\n`)
   if (updated === original) return blocked("Canonical target lacks replaceable Acceptance Criteria and Changelog sections.")
   const rel = relative(root, artifact).split(sep).join("/"), sources = preview.evidence.map((e: any) => `${e.type}: ${e.source}`).join("; "), rows = [`\n| ${preview.id} | Proposal | ${preview.title} | ${sources} | high | approved acceptance criteria update | ${preview.id} | [${preview.id}](${rel}) |\n`, `\n| APPROVAL-${preview.id} | Approved acceptance criteria update ${preview.id}. | Do not persist. | ${sources} | BASS | 2026-08-14 | ${preview.id} | [${preview.id}](${rel}) |\n`, `\n| ACT-${preview.id} | acceptance criteria persistence | ${preview.id} | Approved acceptance criteria update persisted locally. | ${sources} | APPROVAL-${preview.id} | BASS | 2026-08-14 | completed | [${preview.id}](${rel}) |\n`], files = [artifact, ...registers], temps = files.map((p) => `${p}.tmp-${args.previewId}`), backups: string[] = [], originals = [original, ...registers.map((p) => readFileSync(p, "utf8"))]
   try { writeFileSync(temps[0], updated, { encoding: "utf8", flag: "wx" }); for (let i = 0; i < registers.length; i++) writeFileSync(temps[i + 1], originals[i + 1] + rows[i], { encoding: "utf8", flag: "wx" }); for (let i = 0; i < files.length; i++) { const backup = `${files[i]}.bak-${args.previewId}`; renameSync(files[i], backup); backups.push(backup) }; for (let i = 0; i < files.length; i++) renameSync(temps[i], files[i]); backups.forEach((backup) => rmSync(backup, { force: true })); issued.delete(args.previewId); return { status: "persisted", path: artifact, id: preview.id } } catch { for (const temp of temps) rmSync(temp, { force: true }); for (let i = 0; i < backups.length; i++) if (existsSync(backups[i])) { rmSync(files[i], { force: true }); renameSync(backups[i], files[i]) } for (let i = 0; i < files.length; i++) writeFileSync(files[i], originals[i], "utf8"); return blocked("Atomic persistence failed; all staged writes were rolled back.") }
  }
  const parent = preview.artifactType === "proposal" ? join(project, "proposals") : preview.artifactType === "user_story" ? join(preview.parent?.directory || "", "user-stories") : join(project, "features"); if (!preview.parent && preview.artifactType === "user_story") return blocked("User Story preview lacks its canonical parent Feature."); if (preview.artifactType === "user_story" ? !safe(root, preview.parent.directory) : !safe(root, parent)) return blocked("Required canonical artifact parent is unavailable or unsafe.")
  const directory = join(parent, preview.directory), artifact = join(directory, preview.artifactType === "proposal" ? "proposal.md" : preview.artifactType === "user_story" ? "user-story.md" : "feature.md"), registers = [join(project, "evidence-register.md"), join(project, "decision-log.md"), join(project, "action-log.md")]; if (registers.some((p) => !safe(root, p)) || !within(root, parent) || !within(root, directory) || existsSync(directory) || existsSync(artifact)) return blocked("Canonical target, register, collision, or containment preflight failed.")
  const rel = relative(root, artifact).split(sep).join("/"), approval = `\n\n<!-- Approval recorded: explicit local approval for preview ${args.previewId}; payload sha256 ${preview.hash} -->\n`, rows = [`\n| ${preview.id} | Proposal | ${preview.title} | ${preview.evidence.map((e: any) => `${e.type}: ${e.source}`).join("; ")} | high | approved preview | ${preview.id} | [${preview.id}](${rel}) |\n`, `\n| APPROVAL-${preview.id} | Approved local artifact ${preview.id}. | Do not persist. | ${preview.evidence.map((e: any) => `${e.type}: ${e.source}`).join("; ")} | BASS | 2026-08-14 | ${preview.id} | [${preview.id}](${rel}) |\n`, `\n| ACT-${preview.id} | local artifact persistence | ${preview.id} | Approved preview persisted locally. | ${preview.evidence.map((e: any) => `${e.type}: ${e.source}`).join("; ")} | APPROVAL-${preview.id} | BASS | 2026-08-14 | completed | [${preview.id}](${rel}) |\n`]
   const temps = [artifact, ...registers].map((p) => `${p}.tmp-${args.previewId}`), backups: string[] = []; let originals: string[] = [], createdContainer = false; try { originals = registers.map((p) => readFileSync(p, "utf8")); if (preview.artifactType === "user_story" && !existsSync(parent)) { mkdirSync(parent, { recursive: false }); createdContainer = true } if (!safe(root, parent)) throw new Error("unsafe canonical container"); mkdirSync(directory, { recursive: false }); writeFileSync(temps[0], markdown + approval, { encoding: "utf8", flag: "wx" }); for (let i = 0; i < registers.length; i++) writeFileSync(temps[i + 1], originals[i] + rows[i], { encoding: "utf8", flag: "wx" }); for (let i = 0; i < registers.length; i++) { const backup = `${registers[i]}.bak-${args.previewId}`; renameSync(registers[i], backup); backups.push(backup) } renameSync(temps[0], artifact); for (let i = 0; i < registers.length; i++) renameSync(temps[i + 1], registers[i]); for (const backup of backups) rmSync(backup, { force: true }); issued.delete(args.previewId); return { status: "persisted", path: artifact, id: preview.id } } catch { for (const temp of temps) rmSync(temp, { force: true }); if (existsSync(artifact)) rmSync(artifact, { force: true }); for (let i = 0; i < backups.length; i++) if (existsSync(backups[i])) { rmSync(registers[i], { force: true }); renameSync(backups[i], registers[i]) } for (let i = 0; i < originals.length; i++) writeFileSync(registers[i], originals[i], "utf8"); rmSync(directory, { recursive: true, force: true }); if (createdContainer) rmSync(parent, { recursive: false, force: true }); return blocked("Atomic persistence failed; all staged writes were rolled back.") }
} }) } })
