import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { type Plugin, tool } from "@opencode-ai/plugin"

const categories = ["Work Item Search and Filtering", "Hierarchy and Relations", "Comments and History", "Wiki Search and Read"] as const
type Category = typeof categories[number]
type Mapping = { tool_name: string; supported_input: string; verified_read_only: boolean; verification_date: string; valid: boolean }
const section = (text: string, heading: string) => text.match(new RegExp(`^## ${heading.replace("/", "\\/")}[ \\t]*\\r?\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, "m"))?.[1] || ""
const field = (text: string, name: string) => text.match(new RegExp(`^${name}:[ \\t]*(\\S(?:.*\\S)?)[ \\t]*$`, "m"))?.[1].trim() || ""
function validDate(value: string) { const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/); if (!match) return false; const date = new Date(`${value}T00:00:00Z`); return !Number.isNaN(date.valueOf()) && date.getUTCFullYear() === Number(match[1]) && date.getUTCMonth() + 1 === Number(match[2]) && date.getUTCDate() === Number(match[3]) }
function parse(text: string): Record<Category, Mapping> { return Object.fromEntries(categories.map((category) => { const block = section(text, category), tool_name = field(block, "tool_name"), supported_input = field(block, "supported_input"), verification_date = field(block, "verification_date"), verified_read_only = /^verified_read_only:\s*true\s*$/mi.test(block), wellFormed = block.split(/\r?\n/).every((line) => !line.trim() || /^(tool_name|supported_input|verified_read_only|verification_date):/.test(line.trim())); return [category, { tool_name, supported_input, verified_read_only, verification_date, valid: Boolean(wellFormed && /^[A-Za-z0-9_-]+$/.test(tool_name) && supported_input && verified_read_only && validDate(verification_date)) }] })) as Record<Category, Mapping> }
export function validateAdoDiscoveryCapabilities({ projectDirectory, requiredCategories }: { projectDirectory: string; requiredCategories: string[] }) { const path = join(projectDirectory, "project-context", "ado-discovery-capabilities.md"), mappings = parse(existsSync(path) ? readFileSync(path, "utf8") : ""), valid = categories.filter((category) => mappings[category].valid), required = [...new Set(requiredCategories)].filter((category): category is Category => categories.includes(category as Category)); return { mappings, permissionFragment: [`"ado_*": deny`, ...valid.map((category) => `"${mappings[category].tool_name}": allow`)].join("\n"), dispatch: required.filter((category) => mappings[category].valid).map((category) => ({ category, tool_name: mappings[category].tool_name })), unmappedGaps: required.filter((category) => !mappings[category].valid) } }
export const BassValidateAdoDiscoveryCapabilitiesPlugin: Plugin = async () => ({ tool: { bass_validate_ado_discovery_capabilities: tool({ description: "Validate independent read-only ADO discovery mappings without MCP calls.", args: { projectDirectory: tool.schema.string(), requiredCategories: tool.schema.array(tool.schema.string()) }, async execute(args: { projectDirectory: string; requiredCategories: string[] }) { return validateAdoDiscoveryCapabilities(args) } }) } })
